### ISSUE TITLE
BROKEN BUILD: LTC_AES_NI - ltc/ciphers/aes/aes_desc.c:67:13: error: invalid output constraint '=a' in asm

### ISSUE THREAD

**Issue by hookbot** [DCIT/perl-CryptX#112]
How long until this module is working again?

I'll try to get enough details in case this wasn't already a known issue.

So I noticed the build has been broken for a couple months:

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/2742be3d-e8cd-4e93-89ab-6f2de1f4e163">

```
[hookbot@Test-Sequoia-Box perl-CryptX]$ perl Makefile.PL ; time make
[...]
cp lib/Crypt/Digest/BLAKE2s_256.pm blib/lib/Crypt/Digest/BLAKE2s_256.pm
cp lib/Crypt/Mac/Pelican.pm blib/lib/Crypt/Mac/Pelican.pm
cp lib/Crypt/Digest/BLAKE2s_224.pm blib/lib/Crypt/Digest/BLAKE2s_224.pm
cp lib/Crypt/Digest/SHA512.pm blib/lib/Crypt/Digest/SHA512.pm
cp lib/Crypt/Cipher/XTEA.pm blib/lib/Crypt/Cipher/XTEA.pm
cd src && make ARFLAGS="cr" RANLIB="ranlib" AR="ar" CC="cc" LIB_EXT=.a OBJ_EXT=.o CFLAGS="  -g -pipe -DPERL_USE_SAFE_PUTENV   -Os  -DLTC_AES_NI"
cc -Iltm -Iltc/headers -DLTC_SOURCE -DLTC_NO_TEST -DLTC_NO_PROTOTYPES -DLTM_DESC -g -pipe -DPERL_USE_SAFE_PUTENV   -Os  -DLTC_AES_NI -DARGTYPE=4 -c ltc/ciphers/aes/aes.c -o ltc/ciphers/aes/aes.o
cc -Iltm -Iltc/headers -DLTC_SOURCE -DLTC_NO_TEST -DLTC_NO_PROTOTYPES -DLTM_DESC -g -pipe -DPERL_USE_SAFE_PUTENV   -Os  -DLTC_AES_NI -DARGTYPE=4 -c ltc/ciphers/aes/aes_desc.c -o ltc/ciphers/aes/aes_desc.o
ltc/ciphers/aes/aes_desc.c:67:13: error: invalid output constraint '=a' in asm
   67 |            :"=a"(a), "=b"(b), "=c"(c), "=d"(d)
      |             ^
1 error generated.
make[1]: *** [ltc/ciphers/aes/aes_desc.o] Error 1
make: *** [src/liballinone.a] Error 2
```

"git bisect" says that this issue did not exist in 06692976c40cec55fdf691a133b7b13a8e0bd0db, but the bug was born here in 0f4d932aa60d91fcaa6b2a3e959afb6b2fc36340:

```
commit 0f4d932aa60d91fcaa6b2a3e959afb6b2fc36340
Author: Karel Miko <karel.miko@gmail.com>
Date:   Mon Sep 2 16:41:49 2024 +0200

    libtomcrypt update: develop ce904c86
```

Frankly, I'm not familiar with this code nor with XS in general, but here is a one-liner patch that fixed it for me:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/fe7288e0-3944-4b73-a5f3-0401d8a41ca9">
```
diff --git a/Makefile.PL b/Makefile.PL
index 6b1f239d..f05580d4 100644
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -38,7 +38,7 @@ else {
     $ver1 ||= $1 if $Config{gccversion} =~ /^([0-9]+)\./; # gccversion='10.2.0'
     $ver1 ||= $1 if $Config{gccversion} =~ /LLVM ([0-9]+)\./i; # gccversion='Apple LLVM 14.0.0 (clang-1400.0.29.202)'
     $ver1 ||= $1 if $Config{gccversion} =~ /Clang ([0-9]+)\./i; # gccversion='FreeBSD Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a303)' or 'OpenBSD Clang 13.0.0'
-    $mycflags .= " -DLTC_AES_NI" if $ver1 > 4; # target attributes are supported since gcc-4.9
+    $mycflags .= " -DLTC_AES_NI" if $ver1 > 4 && $ver1 < 13; # target attributes are supported since gcc-4.9
   }
 
   #FIX: this is particularly useful for Debian https://github.com/DCIT/perl-CryptX/pull/39
```

But it might be better to actually fix the syntax for the `__asm__` chunks do it's forward compatible with future versions of gcc. Do you need a Pull Request?

$CryptX::VERSION  <= 0.80 - Works everywhere.
$CryptX::VERSION  >= 0.81 - Broken on the newer gcc that I've tried.

Unfortunately, I had to update a new version of gcc in order to build another project, but fortunately perl-CryptX works on the other architectures I've tried.

Here are the details of the machine where it won't build:
<img width="216" alt="image" src="https://github.com/user-attachments/assets/c82bc8de-7a5d-4e78-8159-a43a83eb2a5c">
```
[hookbot@Test-Sequoia-Box perl-CryptX]$ uname -a
Darwin Test-Sequoia-Box.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64
[hookbot@Test-Sequoia-Box perl-CryptX]$
[hookbot@Test-Sequoia-Box perl-CryptX]$
[hookbot@Test-Sequoia-Box perl-CryptX]$ perl -V
Summary of my perl5 (revision 5 version 34 subversion 1) configuration:

  Platform:
    osname=darwin
    osvers=24.0
    archname=darwin-thread-multi-2level
    uname='darwin 5dgj7.p1s.plx.sd.apple.com 24.0 darwin kernel version 22.1.0: thu dec 15 17:42:24 pst 2022; root:xnu-8792.41.9.100.2~1development_x86_64 x86_64 '
    config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=cc'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags =' -g -pipe -DPERL_USE_SAFE_PUTENV'
    optimize='-Os'
    cppflags='-g -pipe'
    ccversion=''
    gccversion='Apple LLVM 16.0.0 (clang-1600.0.25.3) [+internal-os]'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' '
    libpth=/AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.Internal.sdk/usr/local/lib /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Applications/Xcode.app/Contents/Developer/Toolchains/OSX15.1.xctoolchain/usr/lib/clang/16/lib /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.Internal.sdk/usr/lib /AppleInternal/Library/BuildRoots/4b66fb3c-7dd0-11ef-b4fb-4a83e32a47e1/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /usr/local/lib
    libs=
    perllibs=
    libc=
    so=dylib
    useshrplib=true
    libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -bundle -undefined dynamic_lookup'


Characteristics of this binary (from libperl):
Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    /Library/Perl/Updates/<version> comes before system perl directories
    installprivlib and installarchlib points to the Updates directory
  Built under darwin
  Compiled at Sep 28 2024 16:20:11
  @INC:
    /Library/Perl/5.34/darwin-thread-multi-2level
    /Library/Perl/5.34
    /Network/Library/Perl/5.34/darwin-thread-multi-2level
    /Network/Library/Perl/5.34
    /Library/Perl/Updates/5.34.1
    /System/Library/Perl/5.34/darwin-thread-multi-2level
    /System/Library/Perl/5.34
    /System/Library/Perl/Extras/5.34/darwin-thread-multi-2level
    /System/Library/Perl/Extras/5.34
[hookbot@Test-Sequoia-Box perl-CryptX]$
[hookbot@Test-Sequoia-Box perl-CryptX]$ gcc --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
[hookbot@Test-Sequoia-Box perl-CryptX]$
```

Good luck!

**Comment by karel-m** [comment]
Starting with “How long until this module is working again?” is unhelpful and disrespectful. If you want your concerns addressed, approach them professionally. Otherwise, I will close them unsolved like this one.
